---
- name: "ログディレクトリ"
  file:
    path: "{{ postgresql_logdir }}"
    state: "directory"
    owner: "postgres"
    group: "postgres"
    mode: "0755"

- name: "バックアップディレクトリ"
  file:
    path: "{{ postgresql_backupdir }}"
    state: "directory"
    owner: "postgres"
    group: "postgres"
    mode: "0755"

- name: "設定ファイル(postgresql.conf)"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_datadir }}/postgresql.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify: "restart_postgresql"

- name: "設定ファイル(pg_hba.conf)"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_datadir }}/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify: "restart_postgresql"

- name: "ファイアウォール許可設定"
  firewalld:
    service: postgresql
    permanent: yes
    state: enabled
  when: postgresql_firewalld_is_enabled