---
- name: "DBクラスタの初期化"
  shell: "/bin/postgresql-setup initdb"
  environment:
    PGSETUP_INITDB_OPTIONS: "-D {{ postgresql_datadir }} --encoding=UTF-8 --no-locale"
  args:
    creates: "{{ postgresql_datadir }}/PG_VERSION"