---
- name: "パッケージ管理"
  import_tasks: packages.yml

- name: "DBクラスタ作成"
  import_tasks: db_cluster.yml

- name: "設定ファイル管理"
  import_tasks: configurations.yml

- name: "サービス起動状態管理"
  import_tasks: services.yml